create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  player_alias text not null check (char_length(player_alias) between 2 and 30),
  class_code text not null check (char_length(class_code) between 2 and 20),
  total_score integer not null check (total_score >= 0),
  security_score integer not null check (security_score >= 0),
  thinking_score integer not null check (thinking_score >= 0),
  cynefin_score integer not null check (cynefin_score >= 0),
  max_dimension_score integer not null check (max_dimension_score > 0),
  level text not null check (char_length(level) between 2 and 60),
  duration_seconds integer not null check (duration_seconds between 0 and 86400),
  answers jsonb not null default '[]'::jsonb,
  game_version text not null default '2.0'
);

alter table public.admin_users enable row level security;
alter table public.game_results enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.game_results from anon, authenticated;
grant insert on table public.game_results to anon;
grant select, delete on table public.game_results to authenticated;
grant usage, select on sequence public.game_results_id_seq to anon;

create or replace function public.is_game_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_game_admin() from public;
grant execute on function public.is_game_admin() to authenticated;

drop policy if exists "anonymous students can submit results" on public.game_results;
create policy "anonymous students can submit results"
on public.game_results
for insert
to anon
with check (
  char_length(player_alias) between 2 and 30
  and char_length(class_code) between 2 and 20
  and jsonb_typeof(answers) = 'array'
);

drop policy if exists "admins can read results" on public.game_results;
create policy "admins can read results"
on public.game_results
for select
to authenticated
using (public.is_game_admin());

drop policy if exists "admins can delete results" on public.game_results;
create policy "admins can delete results"
on public.game_results
for delete
to authenticated
using (public.is_game_admin());

-- Dopo aver creato l'utente docente in Authentication > Users, eseguire:
-- insert into public.admin_users (user_id) values ('UUID-UTENTE-DOCENTE');
